gpt:
  provider: "openai"
  model_id: "gpt-4o-mini"
  temperature_values: [0.2, 0.8]

llama:
  model_id: "llama3.3-b"
  temperature_values: [0.2, 0.5, 1]

deepseek:
  model_id: "deepseek-r1"
  temperature_values: null